// Static evidence extraction. Requires TypeScript; override TYPESCRIPT_PATH when needed.
const ts=require(process.env.TYPESCRIPT_PATH||'typescript');const fs=require('fs'),path=require('path');const root=process.cwd(),out=path.join(__dirname,'../data');
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}
const files=walk('src').filter(f=>/\.tsx?$/.test(f)&&! /\.(test|spec)\./.test(f));const program=ts.createProgram(files,{baseUrl:root,paths:{'@/*':['src/*']},jsx:ts.JsxEmit.ReactJSX,moduleResolution:ts.ModuleResolutionKind.Bundler,allowSyntheticDefaultImports:true});const checker=program.getTypeChecker();const sources=program.getSourceFiles().filter(s=>s.fileName.startsWith(root+'/src/')||s.fileName.startsWith('src/'));const rel=f=>path.relative(root,path.resolve(f));const line=(s,n)=>s.getLineAndCharacterOfPosition(n.getStart(s)).line+1;const all=[];function visit(n,fn){fn(n);ts.forEachChild(n,x=>visit(x,fn));}
const services=[],calls=[],components=[],contracts=[];const deps={};
for(const s of sources){const file=rel(s.fileName);deps[file]=new Set();visit(s,n=>{
if(ts.isImportDeclaration(n)&&n.importClause){const names=[];if(n.importClause.name)names.push(n.importClause.name);const b=n.importClause.namedBindings;if(b&&ts.isNamedImports(b))names.push(...b.elements.map(x=>x.name));for(const x of names){let sym=checker.getSymbolAtLocation(x);if(sym?.flags&ts.SymbolFlags.Alias)sym=checker.getAliasedSymbol(sym);for(const d of sym?.declarations||[])deps[file].add(rel(d.getSourceFile().fileName));}}
if(ts.isMethodDeclaration(n)&&file.startsWith('src/api/')){const body=n.body?.getText(s)||'';services.push({file,line:line(s,n),method:n.name.getText(s),parameters:n.parameters.map(p=>p.getText(s)),returnType:n.type?.getText(s),baseUrl:s.text.match(/baseUrl\s*=\s*(['"`].*?['"`])/s)?.[1],httpCalls:[...body.matchAll(/(?:AxiosClient|axiosClient|this\.client|this\.apiClient)\.(get|post|put|patch|delete)(?:<[^;]*?>)?\(([^;]*)/g)].map(m=>({verb:m[1],expression:m[2]})),body});}
if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&/Api$/.test(n.expression.expression.getText(s))){calls.push({file,line:line(s,n),service:n.expression.expression.getText(s),method:n.expression.name.text,arguments:n.arguments.map(a=>a.getText(s))});}
if((ts.isInterfaceDeclaration(n)||ts.isTypeAliasDeclaration(n))&&/src\/(types|models)\//.test(file))contracts.push({file,line:line(s,n),name:n.name.text,definition:n.getText(s)});
});
if(file.startsWith('src/components/')||file.startsWith('src/pages/')){const fields=[];visit(s,n=>{if(ts.isJsxSelfClosingElement(n)||ts.isJsxOpeningElement(n)){const tag=n.tagName.getText(s);if(/Input|Select|Textarea|Checkbox|Switch|Form|Button|Dialog|Drawer|Table/.test(tag))fields.push({line:line(s,n),tag,props:n.attributes.getText(s)});}});components.push({file,lines:s.text.split('\n').length,fields,queries:[...s.text.matchAll(/(?:queryKey|mutationKey):\s*([^\n]+)/g)].map(m=>m[1]),propertyReads:[...new Set([...s.text.matchAll(/\b(?:data|response|customer|plan|feature|invoice|subscription|price|wallet|item|row)(?:\?\.|\.)[\w.?]+/g)].map(m=>m[0]))]});}}
const rs=sources.find(s=>rel(s.fileName)==='src/core/routes/Routes.tsx'),constants={};visit(rs,n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(rs)==='RouteNames'&&n.initializer)for(const p of n.initializer.properties)if(ts.isPropertyAssignment(p)&&ts.isStringLiteral(p.initializer))constants[p.name.getText(rs)]=p.initializer.text;});
function evalPath(n){if(ts.isStringLiteral(n))return n.text;if(ts.isPropertyAccessExpression(n))return constants[n.name.text]||n.getText(rs);if(ts.isTemplateExpression(n))return n.head.text+n.templateSpans.map(x=>evalPath(x.expression)+x.literal.text).join('');return n.getText(rs);}
const routes=[];visit(rs,n=>{if(!ts.isObjectLiteralExpression(n))return;const props=Object.fromEntries(n.properties.filter(ts.isPropertyAssignment).map(p=>[p.name.getText(rs),p.initializer]));if(!props.path)return;const own=evalPath(props.path);let parent=n.parent,parentPath='';while(parent){if(ts.isObjectLiteralExpression(parent)){const p=parent.properties.find(x=>ts.isPropertyAssignment(x)&&x.name.getText(rs)==='path');if(p){parentPath=evalPath(p.initializer);break;}}parent=parent.parent;}const full=own.startsWith('/')?own:(parentPath+'/'+own).replace(/\/+/g,'/');const element=props.element?.getText(rs)||'';let file; if(props.element)visit(props.element,x=>{if(file)return;if(ts.isJsxSelfClosingElement(x)||ts.isJsxOpeningElement(x)){let sym=checker.getSymbolAtLocation(x.tagName);if(sym?.flags&ts.SymbolFlags.Alias)sym=checker.getAliasedSymbol(sym);const d=sym?.declarations?.[0];if(d)file=rel(d.getSourceFile().fileName);}});const seen=new Set();function reach(f){if(seen.has(f)||!f?.startsWith('src/')||f==='src/core/routes/Routes.tsx')return;seen.add(f);for(const d of deps[f]||[])reach(d);}reach(file);routes.push({path:full,line:line(rs,n),element,componentFile:file,permission:props.handle?.getText(rs),apiCalls:calls.filter(c=>seen.has(c.file)),dependencyFiles:[...seen],runtimeStatus:'not-yet-verified'});});
for(const [name,value] of Object.entries({routes,services,calls,components,contracts}))fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(value,null,2));
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({sourceFiles:sources.length,routes:routes.length,apiMethods:services.length,apiCallsites:calls.length,componentFiles:components.length,typeContracts:contracts.length},null,2));console.log(fs.readFileSync(path.join(out,'summary.json'),'utf8'));
